//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanoTerm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00.0010000")]
        public global::System.TimeSpan MAX_UPDATE_FREQ {
            get {
                return ((global::System.TimeSpan)(this["MAX_UPDATE_FREQ"]));
            }
            set {
                this["MAX_UPDATE_FREQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("115200")]
        public int BAUD_RATE {
            get {
                return ((int)(this["BAUD_RATE"]));
            }
            set {
                this["BAUD_RATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int MAX_PORT_NUMBER {
            get {
                return ((int)(this["MAX_PORT_NUMBER"]));
            }
            set {
                this["MAX_PORT_NUMBER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\r")]
        public string RETURN_CODE {
            get {
                return ((string)(this["RETURN_CODE"]));
            }
            set {
                this["RETURN_CODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int THREAD_RECONNECT_INTERVAL {
            get {
                return ((int)(this["THREAD_RECONNECT_INTERVAL"]));
            }
            set {
                this["THREAD_RECONNECT_INTERVAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int THREAD_SAVELOG_INTERVAL {
            get {
                return ((int)(this["THREAD_SAVELOG_INTERVAL"]));
            }
            set {
                this["THREAD_SAVELOG_INTERVAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int THREAD_DRAWGRAPH_INTERVAL {
            get {
                return ((int)(this["THREAD_DRAWGRAPH_INTERVAL"]));
            }
            set {
                this["THREAD_DRAWGRAPH_INTERVAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AUTO_RECONNECT {
            get {
                return ((bool)(this["AUTO_RECONNECT"]));
            }
            set {
                this["AUTO_RECONNECT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AUTO_CONNECT {
            get {
                return ((bool)(this["AUTO_CONNECT"]));
            }
            set {
                this["AUTO_CONNECT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AUTO_SAVE {
            get {
                return ((bool)(this["AUTO_SAVE"]));
            }
            set {
                this["AUTO_SAVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SEND_AT_ONCE {
            get {
                return ((bool)(this["SEND_AT_ONCE"]));
            }
            set {
                this["SEND_AT_ONCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TX_TIMESTAMP {
            get {
                return ((bool)(this["TX_TIMESTAMP"]));
            }
            set {
                this["TX_TIMESTAMP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RX_TIMESTAMP {
            get {
                return ((bool)(this["RX_TIMESTAMP"]));
            }
            set {
                this["RX_TIMESTAMP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:01")]
        public global::System.TimeSpan TIMESTAMP_SPAN {
            get {
                return ((global::System.TimeSpan)(this["TIMESTAMP_SPAN"]));
            }
            set {
                this["TIMESTAMP_SPAN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyy/MM/dd HH:mm:ss")]
        public string TIMESTAMP_FORMAT {
            get {
                return ((string)(this["TIMESTAMP_FORMAT"]));
            }
            set {
                this["TIMESTAMP_FORMAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Setting {
            get {
                return ((global::System.Drawing.Point)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SAVE_PATH {
            get {
                return ((string)(this["SAVE_PATH"]));
            }
            set {
                this["SAVE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.IO.Ports.Parity SERIAL_PARITY {
            get {
                return ((global::System.IO.Ports.Parity)(this["SERIAL_PARITY"]));
            }
            set {
                this["SERIAL_PARITY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("One")]
        public global::System.IO.Ports.StopBits SERIAL_STOPBITS {
            get {
                return ((global::System.IO.Ports.StopBits)(this["SERIAL_STOPBITS"]));
            }
            set {
                this["SERIAL_STOPBITS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AUTO_CONNECT_FORMOPENING {
            get {
                return ((bool)(this["AUTO_CONNECT_FORMOPENING"]));
            }
            set {
                this["AUTO_CONNECT_FORMOPENING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.IO.Ports.Handshake SERIAL_HANDSHAKE {
            get {
                return ((global::System.IO.Ports.Handshake)(this["SERIAL_HANDSHAKE"]));
            }
            set {
                this["SERIAL_HANDSHAKE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SERIAL_DTR_ENABLE {
            get {
                return ((bool)(this["SERIAL_DTR_ENABLE"]));
            }
            set {
                this["SERIAL_DTR_ENABLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int SERIAL_DATABITS {
            get {
                return ((int)(this["SERIAL_DATABITS"]));
            }
            set {
                this["SERIAL_DATABITS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("808")]
        public int FORM_WIDTH {
            get {
                return ((int)(this["FORM_WIDTH"]));
            }
            set {
                this["FORM_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("686")]
        public int FORM_HEIGHT {
            get {
                return ((int)(this["FORM_HEIGHT"]));
            }
            set {
                this["FORM_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState FORM_WINDOWSTATE {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["FORM_WINDOWSTATE"]));
            }
            set {
                this["FORM_WINDOWSTATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SEND_FILE_PATH {
            get {
                return ((string)(this["SEND_FILE_PATH"]));
            }
            set {
                this["SEND_FILE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool REMOVE_EMPTY_LOG {
            get {
                return ((bool)(this["REMOVE_EMPTY_LOG"]));
            }
            set {
                this["REMOVE_EMPTY_LOG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TIMESTAMP_LINEHEAD {
            get {
                return ((bool)(this["TIMESTAMP_LINEHEAD"]));
            }
            set {
                this["TIMESTAMP_LINEHEAD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TX_SHOW {
            get {
                return ((bool)(this["TX_SHOW"]));
            }
            set {
                this["TX_SHOW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RX_SHOW {
            get {
                return ((bool)(this["RX_SHOW"]));
            }
            set {
                this["RX_SHOW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BINARY_SHOW {
            get {
                return ((bool)(this["BINARY_SHOW"]));
            }
            set {
                this["BINARY_SHOW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("115200")]
        public string NEWPORT_BAUDRATE {
            get {
                return ((string)(this["NEWPORT_BAUDRATE"]));
            }
            set {
                this["NEWPORT_BAUDRATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8 bit")]
        public string NEWPORT_DATABITS {
            get {
                return ((string)(this["NEWPORT_DATABITS"]));
            }
            set {
                this["NEWPORT_DATABITS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("なし")]
        public string NEWPORT_PARITY {
            get {
                return ((string)(this["NEWPORT_PARITY"]));
            }
            set {
                this["NEWPORT_PARITY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string NEWPORT_STOPBITS {
            get {
                return ((string)(this["NEWPORT_STOPBITS"]));
            }
            set {
                this["NEWPORT_STOPBITS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("なし")]
        public string NEWPORT_HANDSHAKE {
            get {
                return ((string)(this["NEWPORT_HANDSHAKE"]));
            }
            set {
                this["NEWPORT_HANDSHAKE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NEWPORT_SAVEDIRECTORY {
            get {
                return ((string)(this["NEWPORT_SAVEDIRECTORY"]));
            }
            set {
                this["NEWPORT_SAVEDIRECTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NEWPORT_SAVETX {
            get {
                return ((bool)(this["NEWPORT_SAVETX"]));
            }
            set {
                this["NEWPORT_SAVETX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NEWPORT_SAVERX {
            get {
                return ((bool)(this["NEWPORT_SAVERX"]));
            }
            set {
                this["NEWPORT_SAVERX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NEWPORT_TXSHOW {
            get {
                return ((bool)(this["NEWPORT_TXSHOW"]));
            }
            set {
                this["NEWPORT_TXSHOW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NEWPORT_RXSHOW {
            get {
                return ((bool)(this["NEWPORT_RXSHOW"]));
            }
            set {
                this["NEWPORT_RXSHOW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NEWPORT_BINARYSHOW {
            get {
                return ((bool)(this["NEWPORT_BINARYSHOW"]));
            }
            set {
                this["NEWPORT_BINARYSHOW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NEWPORT_LOGENABLE {
            get {
                return ((bool)(this["NEWPORT_LOGENABLE"]));
            }
            set {
                this["NEWPORT_LOGENABLE"] = value;
            }
        }
    }
}
